IMAGE_NAME = "bento/ubuntu-16.04"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.100"
        master.vm.hostname = "master"
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "ansible-playbooks/master-playbook.yml"
            ansible.extra_vars = { node_ip: "192.168.50.100", }
        end
        
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 100}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "ansible-playbooks/node-playbook.yml"
                ansible.extra_vars = { node_ip: "192.168.50.#{i + 100}", }
            end
        end
    end

end